import { useCallback, useEffect, useState } from "react";
import { FiBarChart2, FiBell, FiBox, FiCalendar, FiDownload, FiRefreshCw, FiShoppingCart } from "react-icons/fi";
import Swal from "sweetalert2";
import { api } from "../../../../common/api/api";

type ReportType = "usage" | "stock" | "orders";
type Row = Record<string, string | number | null>;
const configs = {
  usage: { title: "Module Usage Report", subtitle: "Compare adoption across Step Counter, Ecommerce, Service and BBPS.", Icon: FiBarChart2, columns: [["module", "Module"], ["active_users", "Active users"], ["activities", "Activities"], ["usage_share", "Usage share"]] },
  stock: { title: "Stock Report", subtitle: "Monitor inventory across vendors and notify partners before stock runs out.", Icon: FiBox, columns: [["product_name", "Product"], ["company_name", "Vendor"], ["brand_name", "Brand"], ["sku", "SKU"], ["stock", "Stock"], ["variant_attributes", "Variant"], ["action", "Alert"]] },
  orders: { title: "Order Report", subtitle: "Review vendor order volume, fulfilment and revenue performance.", Icon: FiShoppingCart, columns: [["order_ref", "Order"], ["company_name", "Vendor"], ["vendor_total", "Value"], ["shipping_status", "Status"], ["item_count", "Items"], ["created_at", "Created"]] },
} satisfies Record<ReportType, { title: string; subtitle: string; Icon: React.ElementType; columns: string[][] }>;
const money = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" }).format(value);
const show = (key: string, value: Row[string]) => { if (value == null || value === "") return "—"; if (key === "vendor_total") return money(Number(value)); if (key === "usage_share") return `${value}%`; if (key === "created_at") return new Date(String(value)).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }); if (key === "variant_attributes") { try { return Object.values(JSON.parse(String(value))).join(" / ") || "Default"; } catch { return "Default"; } } return String(value).replaceAll("_", " "); };

export default function ManagerReportPage({ type }: { type: ReportType }) {
  const config = configs[type]; const [rows, setRows] = useState<Row[]>([]); const [summary, setSummary] = useState<Record<string, string | number>>({}); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(""); const [fromDate, setFromDate] = useState(""); const [toDate, setToDate] = useState(""); const [alerting, setAlerting] = useState<number | null>(null);
  const load = useCallback(async () => { try { setLoading(true); const response = await api.get(`/manager-reports/${type}`, { params: { search: search.trim() || undefined, fromDate: fromDate || undefined, toDate: toDate || undefined } }); setRows(response.data.rows || []); setSummary(response.data.summary || {}); } catch { setRows([]); await Swal.fire("Unable to load report", "Please check the selected filters and try again.", "error"); } finally { setLoading(false); } }, [fromDate, search, toDate, type]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 350); return () => window.clearTimeout(timer); }, [load]);
  const sendAlert = async (variantId: number) => { try { setAlerting(variantId); await api.post(`/manager-reports/stock/${variantId}/alert`); await Swal.fire({ icon: "success", title: "Alert sent", text: "The vendor has received a low-stock notification.", timer: 1700, showConfirmButton: false }); } catch { await Swal.fire("Alert not sent", "The stock may have changed or the vendor could not be notified.", "error"); } finally { setAlerting(null); } };
  const download = () => { if (!rows.length) return; const esc = (v: string) => `"${v.replaceAll('"', '""')}"`; const columns = config.columns.filter(([key]) => key !== "action"); const csv = [columns.map(([, label]) => esc(label)).join(","), ...rows.map((row) => columns.map(([key]) => esc(show(key, row[key]))).join(","))].join("\n"); const url = URL.createObjectURL(new Blob([`\uFEFF${csv}`], { type: "text/csv" })); const a = document.createElement("a"); a.href=url; a.download=`manager-${type}-report.csv`; a.click(); URL.revokeObjectURL(url); };
  const metrics = type === "usage" ? [["totalActivities", "Total activities"], ["leadingModule", "Leading module"]] : type === "stock" ? [["variants", "Variants"], ["units", "Total units"], ["lowStock", "Below 10"], ["outOfStock", "Out of stock"]] : [["orders", "Orders"], ["revenue", "Revenue"], ["delivered", "Delivered"], ["cancelled", "Cancelled"]];
  return <main className="min-h-full bg-gradient-to-br from-[#fdf8ff] via-white to-[#fff5f8] p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-[1500px] space-y-6"><header className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-[#25103d] via-[#68258d] to-[#c33076] p-6 text-white shadow-[0_24px_65px_rgba(91,33,124,0.24)] sm:p-8"><div className="relative flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div className="flex items-center gap-4"><span className="grid h-14 w-14 place-items-center rounded-2xl border border-white/20 bg-white/10"><config.Icon size={25} /></span><div><p className="text-[10px] font-bold uppercase tracking-[0.24em] text-purple-200">Manager analytics</p><h1 className="mt-1 text-2xl font-extrabold sm:text-3xl">{config.title}</h1><p className="mt-1 text-sm text-purple-100/80">{config.subtitle}</p></div></div><button disabled={!rows.length} onClick={download} className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-bold text-[#68258d] disabled:opacity-50"><FiDownload /> Download CSV</button></div></header>
  <section className={`grid gap-4 sm:grid-cols-2 ${metrics.length > 2 ? "xl:grid-cols-4" : ""}`}>{metrics.map(([key,label]) => <article key={key} className="rounded-2xl border border-purple-100 bg-white p-5 shadow-[0_12px_35px_rgba(67,31,91,0.07)]"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-3 text-2xl font-black text-slate-900">{key === "revenue" ? money(Number(summary[key] || 0)) : String(summary[key] ?? 0)}</p></article>)}</section>
  <section className="rounded-3xl border border-purple-100 bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-[1fr_170px_170px_auto]">{type === "stock" ? <input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search product, vendor, brand or SKU" className="rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm outline-none focus:border-purple-400" /> : <div className="hidden md:block" />}<label className="relative"><FiCalendar className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input type="date" value={fromDate} onChange={(e)=>setFromDate(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-slate-50 py-3 pl-9 pr-2 text-sm" /></label><input type="date" value={toDate} onChange={(e)=>setToDate(e.target.value)} className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 text-sm" /><button onClick={()=>void load()} className="inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-[#852BAF] to-[#FC3F78] px-5 py-3 text-sm font-bold text-white"><FiRefreshCw className={loading ? "animate-spin" : ""} /> Apply</button></div></section>
  <section className="overflow-hidden rounded-3xl border border-purple-100 bg-white shadow-[0_18px_55px_rgba(67,31,91,0.08)]"><div className="overflow-x-auto">{loading ? <div className="grid min-h-72 place-items-center font-bold text-[#852BAF]"><FiRefreshCw className="animate-spin text-2xl" /></div> : !rows.length ? <div className="grid min-h-72 place-items-center text-sm text-slate-400">No report data found.</div> : <table className="min-w-full whitespace-nowrap text-left"><thead className="bg-purple-50/60 text-[10px] font-extrabold uppercase tracking-wider text-slate-500"><tr>{config.columns.map(([key,label])=><th key={key} className="px-5 py-4">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row,index)=><tr key={String(row.variant_id || row.vendor_order_id || row.module || index)} className="hover:bg-purple-50/30">{config.columns.map(([key])=><td key={key} className="px-5 py-4 text-sm text-slate-600">{key === "action" ? Number(row.stock) < 10 ? <button disabled={alerting===Number(row.variant_id)} onClick={()=>void sendAlert(Number(row.variant_id))} className="inline-flex items-center gap-2 rounded-xl bg-red-50 px-3 py-2 text-xs font-bold text-red-600 hover:bg-red-600 hover:text-white disabled:opacity-50"><FiBell />{alerting===Number(row.variant_id)?"Sending...":"Send alert"}</button> : <span className="text-xs font-bold text-emerald-600">Healthy</span> : <span className={key.includes("status") ? "rounded-full bg-purple-50 px-3 py-1.5 text-xs font-bold capitalize text-[#852BAF]" : key === "stock" && Number(row.stock)<10 ? "font-black text-red-600" : key === "product_name" || key === "module" ? "font-bold text-slate-900" : ""}>{show(key,row[key])}</span>}</td>)}</tr>)}</tbody></table>}</div></section></div></main>;
}
