import { useCallback, useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { FiArrowLeft, FiBriefcase, FiCalendar, FiCheckCircle, FiClock, FiFileText, FiMail, FiMapPin, FiPhone, FiRefreshCw, FiUser } from "react-icons/fi";
import { api } from "../../../common/api/api";

type EnquiryStatus = "new" | "contacted" | "converted" | "closed";
interface ServiceEnquiry { id: number; enquiry_ref: string; bundle_id: number | null; name: string; city: string; mobile: string; email: string; status: EnquiryStatus; enquiry_data: Record<string, unknown>; created_at: string; service_name: string | null; variant_name: string | null; variant_title: string | null; bundle_name: string | null; bundle_description: string | null; bundle_banner_image: string | null; }
interface ApiResponse { success: boolean; data: ServiceEnquiry; }
const statusClasses: Record<EnquiryStatus, string> = { new: "border-amber-200 bg-amber-50 text-amber-700", contacted: "border-blue-200 bg-blue-50 text-blue-700", converted: "border-emerald-200 bg-emerald-50 text-emerald-700", closed: "border-slate-200 bg-slate-100 text-slate-600" };

function Detail({ icon: Icon, label, value }: { icon: React.ElementType; label: string; value: string }) { return <div className="flex gap-3 rounded-2xl border border-slate-100 bg-slate-50/70 p-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white text-[#852BAF] shadow-sm"><Icon /></span><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 break-words text-sm font-bold text-slate-800">{value || "—"}</p></div></div>; }

export default function ServiceDetails() {
  const { id } = useParams(); const navigate = useNavigate();
  const [data, setData] = useState<ServiceEnquiry | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [updating, setUpdating] = useState(false);
  const fetchDetails = useCallback(async () => { if (!id) return; try { setLoading(true); setError(""); const res = await api.get<ApiResponse>(`/v1/service-enquiry/${id}`); if (!res.data.success) throw new Error(); setData(res.data.data); } catch { setError("We couldn't load this enquiry. It may no longer be available."); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void fetchDetails(); }, [fetchDetails]);
  const updateStatus = async (status: EnquiryStatus) => { if (!data) return; try { setUpdating(true); const response = await api.put(`/v1/service-enquiry/${data.id}/status`, { status }); if (!response.data.success) throw new Error(); setData({ ...data, status }); } catch { window.alert("Unable to update the enquiry status."); } finally { setUpdating(false); } };

  if (loading) return <div className="grid min-h-[65vh] place-items-center bg-gradient-to-br from-[#fdf8ff] via-white to-[#fff5f8]"><span className="flex flex-col items-center gap-3 text-sm font-bold text-[#852BAF]"><FiRefreshCw className="animate-spin text-3xl" />Loading enquiry details...</span></div>;
  if (error || !data) return <div className="grid min-h-[65vh] place-items-center bg-gradient-to-br from-[#fdf8ff] via-white to-[#fff5f8] p-6 text-center"><div><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-red-50 text-red-500"><FiFileText size={24} /></div><h2 className="mt-4 text-xl font-extrabold text-slate-900">Enquiry unavailable</h2><p className="mt-1 text-sm text-slate-500">{error}</p><button onClick={() => navigate(-1)} className="mt-5 rounded-xl bg-[#852BAF] px-5 py-2.5 text-sm font-bold text-white">Return to enquiries</button></div></div>;

  const requirementEntries = Object.entries(data.enquiry_data || {});
  return <main className="min-h-full bg-gradient-to-br from-[#fdf8ff] via-white to-[#fff5f8] p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6">
    <header className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-[#25103d] via-[#68258d] to-[#c33076] p-6 text-white shadow-[0_24px_65px_rgba(91,33,124,0.24)] sm:p-8"><div className="absolute -right-16 -top-20 h-60 w-60 rounded-full bg-white/10 blur-2xl" /><div className="relative flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><button onClick={() => navigate(-1)} className="mb-5 inline-flex items-center gap-2 rounded-xl border border-white/15 bg-white/10 px-3.5 py-2 text-xs font-bold transition hover:bg-white/20"><FiArrowLeft /> Back to enquiries</button><p className="text-[10px] font-bold uppercase tracking-[0.24em] text-purple-200">Enquiry detail</p><h1 className="mt-1 text-2xl font-extrabold sm:text-3xl">{data.enquiry_ref}</h1><p className="mt-1 text-sm text-purple-100/75">Received {new Date(data.created_at).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })}</p></div><div className="rounded-2xl border border-white/15 bg-white/10 p-4 backdrop-blur-sm"><label className="mb-2 block text-[10px] font-bold uppercase tracking-wider text-purple-200">Update enquiry status</label><select value={data.status} disabled={updating} onChange={(event) => void updateStatus(event.target.value as EnquiryStatus)} className="min-w-52 rounded-xl border border-white/20 bg-white px-4 py-2.5 text-sm font-extrabold capitalize text-slate-800 outline-none"><option value="new">New</option><option value="contacted">Contacted</option><option value="converted">Converted</option><option value="closed">Closed</option></select></div></div></header>
    <section className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-purple-100 bg-white p-5 shadow-[0_12px_35px_rgba(67,31,91,0.07)]"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Current status</p><span className={`mt-3 inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-xs font-extrabold capitalize ${statusClasses[data.status]}`}>{data.status === "converted" ? <FiCheckCircle /> : <FiClock />}{data.status}</span></div><div className="rounded-2xl border border-purple-100 bg-white p-5 shadow-[0_12px_35px_rgba(67,31,91,0.07)]"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Service type</p><p className="mt-3 text-lg font-extrabold text-slate-900">{data.bundle_name ? "Bundle enquiry" : "Individual service"}</p></div><div className="rounded-2xl border border-purple-100 bg-white p-5 shadow-[0_12px_35px_rgba(67,31,91,0.07)]"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Location</p><p className="mt-3 flex items-center gap-2 text-lg font-extrabold text-slate-900"><FiMapPin className="text-[#852BAF]" />{data.city || "Not provided"}</p></div></section>
    <div className="grid gap-6 lg:grid-cols-[0.9fr_1.1fr]">
      <section className="rounded-3xl border border-purple-100 bg-white p-6 shadow-[0_18px_55px_rgba(67,31,91,0.08)]"><div className="mb-5 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-purple-50 text-[#852BAF]"><FiUser /></span><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#852BAF]">Customer</p><h2 className="text-lg font-extrabold text-slate-900">Contact information</h2></div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1 xl:grid-cols-2"><Detail icon={FiUser} label="Full name" value={data.name} /><Detail icon={FiPhone} label="Mobile number" value={data.mobile} /><Detail icon={FiMail} label="Email address" value={data.email} /><Detail icon={FiMapPin} label="City" value={data.city} /></div></section>
      <section className="rounded-3xl border border-purple-100 bg-white p-6 shadow-[0_18px_55px_rgba(67,31,91,0.08)]"><div className="mb-5 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-pink-50 text-[#FC3F78]"><FiBriefcase /></span><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#FC3F78]">Selection</p><h2 className="text-lg font-extrabold text-slate-900">Service information</h2></div></div><div className="grid gap-3 sm:grid-cols-2"><Detail icon={FiBriefcase} label="Service" value={data.service_name || data.bundle_name || "Not specified"} /><Detail icon={FiFileText} label="Variant" value={data.variant_name || "Not applicable"} /><Detail icon={FiFileText} label="Variant title" value={data.variant_title || "Not applicable"} /><Detail icon={FiCalendar} label="Enquiry date" value={new Date(data.created_at).toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" })} /></div>{data.bundle_description && <div className="mt-4 rounded-2xl border border-purple-100 bg-purple-50/50 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-[#852BAF]">Bundle description</p><p className="mt-2 text-sm leading-6 text-slate-600">{data.bundle_description}</p></div>}</section>
    </div>
    <section className="overflow-hidden rounded-3xl border border-purple-100 bg-white shadow-[0_18px_55px_rgba(67,31,91,0.08)]"><div className="border-b border-slate-100 px-6 py-5"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#852BAF]">Customer brief</p><h2 className="mt-1 text-lg font-extrabold text-slate-900">Requirement details</h2></div>{requirementEntries.length ? <div className="grid gap-px bg-slate-100 sm:grid-cols-2">{requirementEntries.map(([key, value]) => <div key={key} className="bg-white p-6"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{key.replaceAll("_", " ")}</p><p className="mt-2 whitespace-pre-wrap text-sm font-semibold leading-6 text-slate-700">{Array.isArray(value) ? value.join(", ") : String(value ?? "—")}</p></div>)}</div> : <div className="p-10 text-center text-sm text-slate-400">No additional requirement details were supplied.</div>}</section>
  </div></main>;
}
