import { FaPlus, FaTrash } from "react-icons/fa";
/* eslint-disable react-refresh/only-export-components */

export type CustomAttributeInputType = "text" | "number" | "select" | "multiselect" | "textarea";
export interface CustomAttributeRow { id: string; key: string; label: string; input_type: CustomAttributeInputType; is_variant: number; is_required: number; values: string[]; }

const fieldClass = "mt-1.5 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-800 outline-none transition focus:border-[#852BAF]/50 focus:ring-4 focus:ring-purple-100";
export const newCustomAttribute = (): CustomAttributeRow => ({ id: crypto.randomUUID(), key: "", label: "", input_type: "text", is_variant: 0, is_required: 0, values: [""] });

export default function CustomAttributeBuilder({ rows, onChange }: { rows: CustomAttributeRow[]; onChange: (rows: CustomAttributeRow[]) => void }) {
  const update = (id: string, patch: Partial<CustomAttributeRow>) => onChange(rows.map((row) => row.id === id ? { ...row, ...patch } : row));
  return <div className="mt-6 rounded-2xl border border-purple-100 bg-purple-50/40 p-4 sm:p-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-extrabold text-slate-800">Custom attributes</p><p className="mt-1 text-xs text-slate-500">Create typed specifications and use option-based fields to generate variants.</p></div><button type="button" onClick={() => onChange([...rows, newCustomAttribute()])} className="inline-flex items-center gap-1.5 rounded-xl bg-[#852BAF] px-3.5 py-2 text-xs font-bold text-white hover:bg-[#6f2393]"><FaPlus size={11} /> Add attribute</button></div>
    {rows.length === 0 ? <p className="mt-4 rounded-xl border border-dashed border-purple-200 bg-white/70 px-4 py-5 text-center text-xs text-slate-400">No custom attributes added.</p> : <div className="mt-4 space-y-4">{rows.map((row, index) => {
      const optionBased = row.input_type === "select" || row.input_type === "multiselect";
      return <div key={row.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="mb-3 flex items-center justify-between"><p className="text-xs font-black uppercase tracking-wider text-slate-500">Attribute {index + 1}</p><button type="button" onClick={() => onChange(rows.filter((item) => item.id !== row.id))} className="grid h-8 w-8 place-items-center rounded-lg border border-red-100 text-red-500 hover:bg-red-50" aria-label="Remove attribute"><FaTrash size={12} /></button></div>
        <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3"><label className="text-xs font-bold text-slate-600">Label<input value={row.label} onChange={(e) => update(row.id, { label: e.target.value })} placeholder="e.g. Fabric type" className={fieldClass} /></label><label className="text-xs font-bold text-slate-600">Input type<select value={row.input_type} onChange={(e) => { const input_type = e.target.value as CustomAttributeInputType; update(row.id, { input_type, is_variant: input_type === "multiselect" ? row.is_variant : 0 }); }} className={fieldClass}><option value="text">Text</option><option value="number">Number</option><option value="select">Select</option><option value="multiselect">Multi select</option><option value="textarea">Textarea</option></select></label>
          <label className="text-xs font-bold text-slate-600">{optionBased ? "Options / variant values" : "Value"}{row.input_type === "textarea" ? <textarea value={row.values[0] || ""} onChange={(e) => update(row.id, { values: [e.target.value] })} rows={2} className={`${fieldClass} resize-none`} /> : <input type={row.input_type === "number" ? "number" : "text"} value={optionBased ? row.values.join(", ") : row.values[0] || ""} onChange={(e) => update(row.id, { values: optionBased ? e.target.value.split(",").map((v) => v.trimStart()) : [e.target.value] })} placeholder={optionBased ? "e.g. Red, Blue, Green" : "Enter value"} className={fieldClass} />}</label></div>
        <div className="mt-3 flex flex-wrap gap-3"><label className="flex cursor-pointer items-center gap-2 rounded-xl border border-emerald-100 bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700"><input type="checkbox" checked={row.is_required === 1} onChange={(e) => update(row.id, { is_required: e.target.checked ? 1 : 0 })} className="accent-emerald-600" /> Required</label><label className="flex cursor-pointer items-center gap-2 rounded-xl border border-purple-100 bg-purple-50 px-3 py-2 text-xs font-bold text-[#852BAF]"><input type="checkbox" checked={row.is_variant === 1} onChange={(e) => update(row.id, { is_variant: e.target.checked ? 1 : 0, input_type: e.target.checked ? "multiselect" : row.input_type })} className="accent-[#852BAF]" /> Use for variants</label></div>
      </div>;
    })}</div>}
  </div>;
}
