const db = require("../../config/database");
const productModel = require("../models/productModel");
const RewardModel = require("../../models/rewardModel");
const { createError } = require("../utils/appError");

const CATALOG_SEARCH_LIMIT = 20;

// Vendor-scoped browsing (the allocation page's ProductPicker, which lists a
// single vendor's whole catalog rather than autocompleting as-you-type)
// needs a higher cap than a typed cross-vendor search — one vendor's product
// count is naturally bounded, a global text search isn't.
const VENDOR_SCOPED_LIMIT = 50;

class ProductQuickCreateService {
  async searchCatalog(query, vendorId) {
    const limit = vendorId ? VENDOR_SCOPED_LIMIT : CATALOG_SEARCH_LIMIT;
    return productModel.searchCatalog(query, vendorId, limit);
  }

  // SKU is always auto-generated by productModel.createQuick — never
  // accepted from the caller, so every quick-created product gets one
  // consistent with the main catalog's RP-<productId>-<random> scheme.
  //
  // rewardRuleId is optional: when given, the newly created product is
  // immediately mapped to that reward rule (product-level target, matching
  // ProductRewardMapping.tsx's "Product" target type) via the same
  // RewardModel.mapRewardToProduct the vendor-manager screen uses — so a
  // flea market manager doesn't have to leave this drawer (and doesn't have
  // access to the vendor_manager-only mapping screen) to make a brand-new
  // product instantly redeemable. This runs AFTER the product/variant
  // transaction commits — the product exists either way, so a mapping
  // failure is surfaced via rewardMappingFailed rather than rolling back
  // product creation.
  async quickCreate({ vendorId, productName, brandName, categoryId, subcategoryId, mrp, salePrice, initialStock, rewardRuleId }) {
    if (mrp == null || salePrice == null || initialStock == null) {
      throw createError(400, "mrp, salePrice and initialStock are required");
    }

    const conn = await db.getConnection();
    let result;
    try {
      await conn.beginTransaction();

      result = await productModel.createQuick(
        { vendorId, productName, brandName, categoryId, subcategoryId, mrp, salePrice, initialStock },
        conn,
      );

      await conn.commit();
    } catch (err) {
      await conn.rollback();
      if (err.code === "ER_DUP_ENTRY") {
        throw createError(409, "A product with this SKU already exists");
      }
      throw err;
    } finally {
      conn.release();
    }

    let rewardMappingFailed = false;
    if (rewardRuleId) {
      try {
        await RewardModel.mapRewardToProduct({
          product_id: result.productId,
          reward_rule_id: rewardRuleId,
          can_earn_reward: 1,
          can_redeem_reward: 1,
        });
      } catch (err) {
        console.error("[flea-market][quick-create] reward rule mapping failed:", err);
        rewardMappingFailed = true;
      }
    }

    return {
      ...result,
      productName,
      brandName: brandName || null,
      mrp: Number(mrp),
      salePrice: Number(salePrice),
      stock: Number(initialStock),
      rewardMappingFailed,
    };
  }
}

module.exports = new ProductQuickCreateService();
