const db = require("../../config/database");
const productModel = require("../models/productModel");
const RewardModel = require("../../models/rewardModel");
const { createError } = require("../utils/appError");

const CATALOG_SEARCH_LIMIT = 20;

// Vendor-scoped browsing (the allocation page's ProductPicker, which lists a
// single vendor's whole catalog rather than autocompleting as-you-type)
// needs a higher cap than a typed cross-vendor search — one vendor's product
// count is naturally bounded, a global text search isn't.
const VENDOR_SCOPED_LIMIT = 50;

class ProductQuickCreateService {
  async searchCatalog(query, vendorId) {
    const limit = vendorId ? VENDOR_SCOPED_LIMIT : CATALOG_SEARCH_LIMIT;
    return productModel.searchCatalog(query, vendorId, limit);
  }

  // SKU is always auto-generated by productModel.createQuick — never
  // accepted from the caller, so every quick-created product gets one
  // consistent with the main catalog's RP-<productId>-<random> scheme.
  //
  // rewardRuleId is optional: when given, the newly created product is
  // immediately mapped to that reward rule (product-level target, matching
  // ProductRewardMapping.tsx's "Product" target type) via the same
  // RewardModel.mapRewardToProduct the vendor-manager screen uses — so a
  // flea market manager doesn't have to leave this drawer (and doesn't have
  // access to the vendor_manager-only mapping screen) to make a brand-new
  // product instantly redeemable. This runs AFTER the product/variant
  // transaction commits — the product exists either way, so a mapping
  // failure is surfaced via rewardMappingFailed rather than rolling back
  // product creation.
  // `variants` (optional array, see productModel.createQuick) is the
  // multi-variant path; when absent, the old flat mrp/salePrice/initialStock
  // fields drive a single variant exactly as before — full backward
  // compatibility, nothing about the single-variant caller's shape changes.
  async quickCreate({ vendorId, productName, brandName, categoryId, subcategoryId, mrp, salePrice, initialStock, rewardRuleId, variants }) {
    const hasVariants = Array.isArray(variants) && variants.length > 0;
    if (!hasVariants && (mrp == null || salePrice == null || initialStock == null)) {
      throw createError(400, "mrp, salePrice and initialStock are required");
    }

    const conn = await db.getConnection();
    let result;
    try {
      await conn.beginTransaction();

      result = await productModel.createQuick(
        { vendorId, productName, brandName, categoryId, subcategoryId, mrp, salePrice, initialStock, variants },
        conn,
      );

      await conn.commit();
    } catch (err) {
      await conn.rollback();
      if (err.code === "ER_DUP_ENTRY") {
        throw createError(409, "A product with this SKU already exists");
      }
      throw err;
    } finally {
      conn.release();
    }

    // Reward mapping stays product-level and is called exactly once
    // regardless of how many variants were created — unchanged.
    let rewardMappingFailed = false;
    if (rewardRuleId) {
      try {
        await RewardModel.mapRewardToProduct({
          product_id: result.productId,
          reward_rule_id: rewardRuleId,
          can_earn_reward: 1,
          can_redeem_reward: 1,
        });
      } catch (err) {
        console.error("[flea-market][quick-create] reward rule mapping failed:", err);
        rewardMappingFailed = true;
      }
    }

    // Top-level mrp/salePrice/stock mirror the FIRST variant — this is what
    // makes the response backward compatible for every existing caller,
    // which only ever created (and reads) a single variant.
    const firstVariant = result.variants[0];

    return {
      productId: result.productId,
      variantId: result.variantId,
      sku: result.sku,
      productName,
      brandName: brandName || null,
      mrp: firstVariant.mrp,
      salePrice: firstVariant.salePrice,
      stock: firstVariant.stock,
      variants: result.variants,
      rewardMappingFailed,
    };
  }
}

module.exports = new ProductQuickCreateService();
