// import { list } from "postcss";

export const routes = {
  vendor: {
    dashboard: "/vendor/dashboard",
    onboarding: "/vendor/onboarding",
    changePassword: "/vendor/change-password",
   products: {
    add: "/vendor/products/add",
    list: "/vendor/products/list",
    edit: "/vendor/products/edit/:id",
    manageProduct:"/vendor/products/manage-product/:productId",
    variantEdit:"/vendor/products/variant-edit/:variantId",
    variantImage:"/vendor/products/variant-image/:variantId",
    review: "/vendor/products/review/:productId", 
    },
    orders:{
      summary: "/vendor/orders/summary",
      details: "/vendor/orders/details/:orderId",
    },
    productManagerList: "/vendor/product-managers",
    fleaMarketPurchases: "/vendor/flea-market/purchases",
  },
   manager: {
    dashboard: "/manager/dashboard",
    changePassword: "/manager/change-password",
    vendors: "/manager/vendors",
    employees: "/manager/employees",
    companyEmployees: "/manager/companies/:companyId/employees",
    products: "/manager/products",
    productView: "/manager/product/:id",
    vendorReview: "/manager/vendor-review/:id",
    categories: "/manager/category_management/categories",
    subcategories: "/manager/category_management/subcategories",
    subsubcategories: "/manager/category_management/subsubcategories",
    addDocument:"/manager/document/DocumentAdd",
    linkDocument:"/manager/document/DocumentCategory",
    attributes: "/manager/attributes",
    // flashlist: "/manager/flashlist",
    // flashCreate: "/manager/flash-sale",
    orders:{
      orderList: "/manager/orders",
      details: "/manager/order-view/:orderId",
      cancellationRequest: "/manager/cancellation-request",
      cancellationDetail: "/manager/cancellation-detail/:orderId",
    },
    services:{
      enquiries:"/manager/enquiries",
      details: "/manager/enquiry/:id",
      service_orders: "/manager/service-orders",
      service_order_details: "/manager/service-order-details/:parentOrderId",
      cancellation_requests: "/manager/service-cancellation-requests",
      cancellation_detail: "/manager/service-cancellation-detail/:serviceOrderId",
    },
    rewards:{
      rewardRule:"/manager/rewards-rule",
      create:"/manager/reward-create",
      edit:"/manager/reward-edit/:id",
      mapping:"/manager/reward-mapping",
    },
    servicePartners: {
      list: "/manager/service-partners",
      onboard: "/manager/service-partners/onboard",
      edit: "/manager/service-partners/edit/:id",
      profile: "/manager/service-partners/:id",
    },
    partnerManagers: {
      list: "/manager/partner-managers",
      onboard: "/manager/partner-managers/onboard",
      edit: "/manager/partner-managers/edit/:id",
    },
  },
  admin: {
    dashboard: "/admin/dashboard",
    changePassword: "/admin/change-password",
    vendors: "/admin/vendors",
    products: "/admin/products",
    services: "/admin/services",
    productView: "/admin/product/:id",
    vendorReview: "/admin/vendor-review/:id",
  
  },
  warehouse: {
    dashboard: "/warehouse/dashboard",
  },
  fleaMarket: {
    dashboard: "/flea-market/dashboard",
    changePassword: "/flea-market/change-password",
    manageEvent: "/flea-market/manage-event",
    billing: {
      page: "/flea-market/billing",
    },
    stock: "/flea-market/manager/stock",
    allProducts: "/flea-market/manager/products",
    reports: {
      vendorSales: "/flea-market/reports/vendor-sales",
      purchaseHistory: "/flea-market/reports/purchase-history",
    },
    invoices: {
      detail: "/flea-market/invoices/:invoiceId",
    },
  },
  hr: {
    dashboard: "/hr/dashboard",
    changePassword: "/hr/change-password",
    onboarding: "/hr/onboarding",
    employees: "/hr/employees",
      rewards: "/hr/rewards",

  },
  service: {
    dashboard: "/service/dashboard",
    servicePartners: {
      list: "/service/service-partners",
      onboard: "/service/service-partners/onboard",
      edit: "/service/service-partners/edit/:id",
      profile: "/service/service-partners/:id",
    },
    partnerManagers: {
      list: "/service/partner-managers",
      onboard: "/service/partner-managers/onboard",
      edit: "/service/partner-managers/edit/:id",
    },
    serviceListings: "/service/service-listings",
    bookings: "/service/bookings",
    reports: "/service/reports",
    settings: "/service/settings",
  },
  servicePartner: {
    dashboard: "/service-partner/dashboard",
    onboarding: "/service-partner/onboarding",
    changePassword: "/service-partner/change-password",
    profile: "/service-partner/profile",
    services: {
      list: "/service-partner/services",
      add: "/service-partner/services/add",
      edit: "/service-partner/services/edit/:id",
    },
    rateCard: "/service-partner/rate-card",
    bookings: {
      list: "/service-partner/bookings",
      details: "/service-partner/bookings/:bookingId",
    },
    reviews: "/service-partner/reviews",
    documents: "/service-partner/documents",
    settings: "/service-partner/settings",
  },
};
