import { FiActivity, FiShield, FiTrendingUp } from "react-icons/fi";
import { Link, useParams } from "react-router-dom";
import { routes } from "../../../../routes";

export default function FinancialServicesPage() {
  const { section = "mutual-funds" } = useParams();
  const insurance = section === "insurance";
  return <main className="space-y-6"><header className="rounded-3xl bg-gradient-to-br from-[#25103d] via-[#68258d] to-[#c33076] p-7 text-white shadow-[0_24px_65px_rgba(91,33,124,0.24)]"><p className="text-[10px] font-bold uppercase tracking-[0.24em] text-purple-200">Financial services</p><h1 className="mt-1 text-3xl font-black">Mutual Funds & Insurance</h1><p className="mt-2 text-sm text-purple-100/80">A dedicated workspace for financial-service content and customer journeys.</p></header><nav className="flex gap-2 rounded-2xl border border-purple-100 bg-white p-2 shadow-sm"><Link to={routes.service.finance.replace(":section?", "mutual-funds")} className={`flex-1 rounded-xl px-4 py-3 text-center text-sm font-extrabold ${!insurance ? "bg-[#852BAF] text-white" : "text-slate-500 hover:bg-purple-50"}`}>Mutual Funds</Link><Link to={routes.service.finance.replace(":section?", "insurance")} className={`flex-1 rounded-xl px-4 py-3 text-center text-sm font-extrabold ${insurance ? "bg-[#852BAF] text-white" : "text-slate-500 hover:bg-purple-50"}`}>Insurance</Link></nav><section className="rounded-3xl border border-purple-100 bg-white p-8 shadow-sm"><span className={`grid h-14 w-14 place-items-center rounded-2xl ${insurance ? "bg-blue-50 text-blue-600" : "bg-emerald-50 text-emerald-600"}`}>{insurance ? <FiShield size={25} /> : <FiTrendingUp size={25} />}</span><h2 className="mt-5 text-2xl font-black text-slate-900">{insurance ? "Insurance" : "Mutual Funds"}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{insurance ? "Manage the insurance experience and monitor its customer enquiry workflow from this section." : "Manage mutual-fund sections, educational content and the customer discovery experience from this section."}</p><div className="mt-6 inline-flex items-center gap-2 rounded-xl bg-purple-50 px-4 py-2.5 text-xs font-bold text-[#852BAF]"><FiActivity /> Module connected to the service workspace</div></section></main>;
}
