const swaggerJsdoc = require("swagger-jsdoc");

const options = {
  definition: {
    openapi: "3.0.0",
    info: {
      title: "Reward Planners API",
      version: "1.0.0",
      description: "Reward Planners Backend APIs",
    },

    servers: [
      {
        url:
          process.env.SWAGGER_SERVER_URL ||
          process.env.BACKEND_URL ||
          "http://localhost:5000",
      },
    ],

    tags: [
      { name: "Mobile App / BBPS / Bills", description: "Mobile BBPS bill and operator APIs" },
      { name: "Mobile App / BBPS / Payments", description: "Mobile BBPS payment APIs" },
      { name: "Mobile App / Common / Auth", description: "Mobile authentication and account APIs" },
      { name: "Mobile App / Common / Global", description: "Mobile global search and app status APIs" },
      { name: "Mobile App / Common / Notification", description: "Mobile notification APIs" },
      { name: "Mobile App / Common / Settings", description: "Mobile settings APIs" },
      { name: "Mobile App / Common / Support", description: "Mobile support APIs" },
      { name: "Mobile App / Common / Terms", description: "Mobile terms and privacy APIs" },
      { name: "Mobile App / Common / Todo", description: "Mobile todo APIs" },
      { name: "Mobile App / Common / Wallet", description: "Mobile common wallet APIs" },
      { name: "Mobile App / Ecommerce / Cart", description: "Mobile ecommerce cart APIs" },
      { name: "Mobile App / Ecommerce / Checkout", description: "Mobile ecommerce checkout APIs" },
      { name: "Mobile App / Ecommerce / Logistics", description: "Mobile ecommerce logistics APIs" },
      { name: "Mobile App / Ecommerce / Orders", description: "Mobile ecommerce order APIs" },
      { name: "Mobile App / Ecommerce / Payment", description: "Mobile ecommerce payment APIs" },
      { name: "Mobile App / Ecommerce / Product", description: "Mobile ecommerce product APIs" },
      { name: "Mobile App / Ecommerce / Review", description: "Mobile ecommerce review APIs" },
      { name: "Mobile App / Ecommerce / Wishlist", description: "Mobile ecommerce wishlist APIs" },
      { name: "Mobile App / Games / Sudoku", description: "Mobile game APIs" },
      { name: "Mobile App / Service / Banner", description: "Mobile service banner APIs" },
      { name: "Mobile App / Service / Bundle", description: "Mobile service bundle APIs" },
      { name: "Mobile App / Service / Cart", description: "Mobile service cart APIs" },
      { name: "Mobile App / Service / Category", description: "Mobile service category APIs" },
      { name: "Mobile App / Service / Checkout", description: "Mobile service checkout APIs" },
      { name: "Mobile App / Service / Document", description: "Mobile service document APIs" },
      { name: "Mobile App / Service / Enquiry", description: "Mobile service enquiry APIs" },
      { name: "Mobile App / Service / Form", description: "Mobile service form APIs" },
      { name: "Mobile App / Service / Insurance", description: "Mobile insurance APIs" },
      { name: "Mobile App / Service / Mutual Fund", description: "Mobile mutual fund APIs" },
      { name: "Mobile App / Service / Order Documents", description: "Mobile service order document APIs" },
      { name: "Mobile App / Service / Orders", description: "Mobile service order APIs" },
      { name: "Mobile App / Service / Service", description: "Mobile service listing APIs" },
      { name: "Mobile App / Service / Variant", description: "Mobile service variant APIs" },
      { name: "Mobile App / Step Counter / Achievement", description: "Mobile achievement APIs" },
      { name: "Mobile App / Step Counter / Dashboard", description: "Mobile fitness dashboard APIs" },
      { name: "Mobile App / Step Counter / Profile", description: "Mobile fitness profile APIs" },
      { name: "Mobile App / Step Counter / Progress", description: "Mobile fitness progress APIs" },
      { name: "Mobile App / Step Counter / Stats", description: "Mobile fitness stats APIs" },
      { name: "Mobile App / Step Counter / Steps", description: "Mobile step sync APIs" },
      { name: "Mobile App / Step Counter / Wallet", description: "Mobile step wallet APIs" },
      { name: "Web Dashboard / Auth", description: "Dashboard authentication APIs" },
      { name: "Web Dashboard / Category", description: "Dashboard category APIs" },
      { name: "Web Dashboard / Company", description: "Dashboard company APIs" },
      { name: "Web Dashboard / Flash", description: "Dashboard flash sale APIs" },
      { name: "Web Dashboard / Logistics", description: "Dashboard logistics APIs" },
      { name: "Web Dashboard / Maintenance", description: "Dashboard maintenance APIs" },
      { name: "Web Dashboard / Manager", description: "Dashboard manager and vendor manager APIs" },
      { name: "Web Dashboard / Offer", description: "Dashboard offer APIs" },
      { name: "Web Dashboard / Order", description: "Dashboard order APIs" },
      { name: "Web Dashboard / Product", description: "Dashboard product APIs" },
      { name: "Web Dashboard / Reward", description: "Dashboard reward APIs" },
      { name: "Web Dashboard / Subcategory", description: "Dashboard subcategory APIs" },
      { name: "Web Dashboard / Subsubcategory", description: "Dashboard sub-subcategory APIs" },
      { name: "Web Dashboard / Variant", description: "Dashboard product variant APIs" },
      { name: "Web Dashboard / Vendor", description: "Dashboard vendor APIs" },
      { name: "Web Dashboard / Warehouse", description: "Dashboard warehouse APIs" },
    ],

    "x-tagGroups": [
      {
        name: "Mobile App",
        tags: [
          "Mobile App / BBPS / Bills",
          "Mobile App / BBPS / Payments",
          "Mobile App / Common / Auth",
          "Mobile App / Common / Global",
          "Mobile App / Common / Notification",
          "Mobile App / Common / Settings",
          "Mobile App / Common / Support",
          "Mobile App / Common / Terms",
          "Mobile App / Common / Todo",
          "Mobile App / Common / Wallet",
          "Mobile App / Ecommerce / Cart",
          "Mobile App / Ecommerce / Checkout",
          "Mobile App / Ecommerce / Logistics",
          "Mobile App / Ecommerce / Orders",
          "Mobile App / Ecommerce / Payment",
          "Mobile App / Ecommerce / Product",
          "Mobile App / Ecommerce / Review",
          "Mobile App / Ecommerce / Wishlist",
          "Mobile App / Games / Sudoku",
          "Mobile App / Service / Banner",
          "Mobile App / Service / Bundle",
          "Mobile App / Service / Cart",
          "Mobile App / Service / Category",
          "Mobile App / Service / Checkout",
          "Mobile App / Service / Document",
          "Mobile App / Service / Enquiry",
          "Mobile App / Service / Form",
          "Mobile App / Service / Insurance",
          "Mobile App / Service / Mutual Fund",
          "Mobile App / Service / Order Documents",
          "Mobile App / Service / Orders",
          "Mobile App / Service / Service",
          "Mobile App / Service / Variant",
          "Mobile App / Step Counter / Achievement",
          "Mobile App / Step Counter / Dashboard",
          "Mobile App / Step Counter / Profile",
          "Mobile App / Step Counter / Progress",
          "Mobile App / Step Counter / Stats",
          "Mobile App / Step Counter / Steps",
          "Mobile App / Step Counter / Wallet",
        ],
      },
      {
        name: "Web Dashboard",
        tags: [
          "Web Dashboard / Auth",
          "Web Dashboard / Category",
          "Web Dashboard / Company",
          "Web Dashboard / Flash",
          "Web Dashboard / Logistics",
          "Web Dashboard / Maintenance",
          "Web Dashboard / Manager",
          "Web Dashboard / Offer",
          "Web Dashboard / Order",
          "Web Dashboard / Product",
          "Web Dashboard / Reward",
          "Web Dashboard / Subcategory",
          "Web Dashboard / Subsubcategory",
          "Web Dashboard / Variant",
          "Web Dashboard / Vendor",
          "Web Dashboard / Warehouse",
        ],
      },
    ],

    components: {
      securitySchemes: {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT",
        },
      },
    },

    security: [
      {
        bearerAuth: [],
      },
    ],
  },

  apis: [
    "./swagger/route-catalog.yaml",
    // "./mps-connect/**/routes/*.js",
  ],
};

const swaggerSpec = swaggerJsdoc(options);

module.exports = swaggerSpec;
