const notificationCatalog = {
  todo_15min: {
    module: "todo",
    type: "todo_reminder",
    title: "Upcoming Task: Review Project Code",
    message: "Starts in 15 minutes at 10:30 AM!",
    icon: "clock",
    reference_type: "todo",
    reference_id: "test_todo_1",
    action_url: "/todo",
    screen: "TodoList",
  },
  todo_custom: {
    module: "todo",
    type: "todo_reminder",
    title: "Reminder: Review Project Code",
    message: "Starts at 10:30 AM!",
    icon: "clock",
    reference_type: "todo",
    reference_id: "test_todo_2",
    action_url: "/todo",
    screen: "TodoList",
  },
  birthday: {
    module: "birthday",
    type: "birthday_wish",
    title: "Happy Birthday, Valued Team Member!",
    message: "Wishing you a fantastic day filled with joy and success! - Reward Planners",
    icon: "gift",
    reference_type: "birthday",
    reference_id: "test_bday_1",
    action_url: "/profile",
    screen: "Profile",
  },
  order_confirmed: {
    module: "ecommerce",
    type: "order_confirmed",
    title: "Order Confirmed!",
    message: "Thank you! Order #98765 has been placed. We are preparing it for shipment.",
    icon: "check-circle",
    reference_type: "order",
    reference_id: "98765",
    action_url: "/orders/order-details/98765",
    screen: "OrderDetails",
  },
  order_dispatched: {
    module: "ecommerce",
    type: "order_dispatched",
    title: "Your order is on the way!",
    message: "Order #98765 has been shipped! Track it using ID: EB12345678.",
    icon: "truck",
    reference_type: "order",
    reference_id: "98765",
    action_url: "/orders/order-details/98765",
    screen: "OrderDetails",
  },
  order_out_for_delivery: {
    module: "ecommerce",
    type: "order_out_for_delivery",
    title: "Out for delivery today",
    message: "Your package #98765 is out for delivery with our executive today.",
    icon: "truck",
    reference_type: "order",
    reference_id: "98765",
    action_url: "/orders/order-details/98765",
    screen: "OrderDetails",
  },
  order_delivered: {
    module: "ecommerce",
    type: "order_delivered",
    title: "Delivered!",
    message: "Your package #98765 has been successfully delivered. Hope you love it!",
    icon: "gift",
    reference_type: "order",
    reference_id: "98765",
    action_url: "/orders/order-details/98765",
    screen: "OrderDetails",
  },
  order_rto: {
    module: "ecommerce",
    type: "order_rto",
    title: "Order returned",
    message: "Your order #98765 could not be delivered and is being returned.",
    icon: "alert-triangle",
    reference_type: "order",
    reference_id: "98765",
    action_url: "/orders/order-details/98765",
    screen: "OrderDetails",
  },
  order_ndr: {
    module: "ecommerce",
    type: "order_ndr",
    title: "Delivery failed",
    message: "We couldn't deliver your order #98765. Please update your details to retry.",
    icon: "x-circle",
    reference_type: "order",
    reference_id: "98765",
    action_url: "/orders/order-details/98765",
    screen: "OrderDetails",
  },
  reward_coins_credit: {
    module: "wallet",
    type: "coins_credited",
    title: "Coins Credited!",
    message: "You earned 150 Reward Coins from your purchase! Check your wallet.",
    icon: "wallet",
    reference_type: "wallet",
    reference_id: "coins_150",
    action_url: "/wallet",
    screen: "Wallet",
  },
  ecommerce_checkout_abandonment: {
    module: "ecommerce",
    type: "payment_abandoned",
    title: "Payment incomplete",
    message: "Your e-commerce order is waiting! Complete your payment of Rs. 1,500 now.",
    icon: "credit-card",
    reference_type: "razorpay_order",
    reference_id: "order_mock_eco123",
    action_url: "/orders",
    screen: "Orders",
  },
  cart_abandonment: {
    module: "ecommerce",
    type: "cart_abandonment",
    title: "Did you forget something?",
    message: "Your cart is waiting! Complete your checkout now and secure your rewards.",
    icon: "shopping-cart",
    reference_type: "cart",
    reference_id: "cart_abandon",
    action_url: "/cart",
    screen: "Cart",
  },
  price_drop: {
    module: "ecommerce",
    type: "cart_price_drop",
    title: "Price Drop!",
    message: "An item in your cart, Premium Smartwatch, is now cheaper! Tap to order now.",
    icon: "trending-down",
    reference_type: "product_variant",
    reference_id: "variant_watch_1",
    action_url: "/cart",
    screen: "Cart",
  },
  low_stock: {
    module: "ecommerce",
    type: "cart_low_stock",
    title: "Almost gone!",
    message: "Hurry! The Premium Smartwatch in your cart is selling fast. Only 2 left!",
    icon: "alert-triangle",
    reference_type: "product_variant",
    reference_id: "variant_watch_1",
    action_url: "/cart",
    screen: "Cart",
  },
  service_confirmed: {
    module: "service",
    type: "service_confirmed",
    title: "Service order confirmed",
    message: "Your order for GST Return Filing is confirmed and we are ready to begin.",
    icon: "briefcase",
    reference_type: "service_order",
    reference_id: "order_srv_1",
    action_url: "/orders/order-details/order_srv_1",
    screen: "OrderDetails",
  },
  service_docs_pending: {
    module: "service",
    type: "service_docs_pending",
    title: "Action Required: Documents pending",
    message: "We found an issue with your documents for GST Return Filing. Tap to review and re-upload.",
    icon: "file-text",
    reference_type: "service_order",
    reference_id: "order_srv_1",
    action_url: "/orders/order-details/order_srv_1",
    screen: "OrderDetails",
  },
  service_docs_submitted: {
    module: "service",
    type: "service_docs_submitted",
    title: "Documents submitted successfully",
    message: "We have received your documents for GST Return Filing and our team is on it.",
    icon: "check-circle",
    reference_type: "service_order",
    reference_id: "order_srv_1",
    action_url: "/orders/order-details/order_srv_1",
    screen: "OrderDetails",
  },
  service_status_updated: {
    module: "service",
    type: "service_status_updated",
    title: "Service status updated",
    message: "Your order for GST Return Filing has been updated to: in_progress.",
    icon: "activity",
    reference_type: "service_order",
    reference_id: "order_srv_1",
    action_url: "/orders/order-details/order_srv_1",
    screen: "OrderDetails",
  },
  service_enquiry_received: {
    module: "service",
    type: "service_enquiry_submitted",
    title: "Enquiry submitted",
    message: "Your service enquiry has been submitted. Our team will contact you soon.",
    icon: "help-circle",
    reference_type: "service_enquiry",
    reference_id: "enq_1",
    action_url: "/services",
    screen: "Services",
  },
  service_checkout_abandonment: {
    module: "service",
    type: "payment_abandoned",
    title: "Service order pending",
    message: "Finish your service order of Rs. 3,500 to let our experts start working.",
    icon: "credit-card",
    reference_type: "razorpay_order",
    reference_id: "order_mock_srv456",
    action_url: "/orders",
    screen: "Orders",
  },
  service_cart_abandonment: {
    module: "service",
    type: "service_cart_abandon",
    title: "Complete your service request!",
    message: "You have service items left in your cart. Let our experts assist you today!",
    icon: "briefcase",
    reference_type: "service_cart",
    reference_id: "service_cart_abandon",
    action_url: "/cart",
    screen: "Cart",
  },
  service_bundle_upsell: {
    module: "service",
    type: "service_bundle_upsell",
    title: "Get the complete package!",
    message: "Save by adding Income Tax Return to complete your Corporate Setup pack!",
    icon: "gift",
    reference_type: "service_bundle",
    reference_id: "bundle_corp_1",
    action_url: "/services",
    screen: "Services",
  },
  missing_document_reminder_24h: {
    module: "service",
    type: "service_missing_docs",
    title: "Urgent: Upload Documents",
    message: "We need your documents to begin work on GST Return Filing. Tap to upload now.",
    icon: "alert-circle",
    reference_type: "service_order",
    reference_id: "order_srv_1",
    action_url: "/orders/order-details/order_srv_1",
    screen: "OrderDetails",
  },
  bbps_checkout_abandonment: {
    module: "bbps",
    type: "payment_abandoned",
    title: "Utility bill payment pending",
    message: "Your bill payment of Rs. 850 was not finished. Tap here to complete it.",
    icon: "credit-card",
    reference_type: "razorpay_order",
    reference_id: "order_mock_bbp789",
    action_url: "/orders",
    screen: "Orders",
  },
  bill_due_reminder: {
    module: "bbps",
    type: "bbps_bill_due",
    title: "Bill Due Alert",
    message: "Your electricity/gas bill is due soon. Pay via Reward Planners and earn double coins!",
    icon: "zap",
    reference_type: "bbps_bill",
    reference_id: "bill_fetch_1",
    action_url: "/bbps",
    screen: "BBPS",
  },
  recharge_reminder: {
    module: "bbps",
    type: "bbps_recharge_reminder",
    title: "Prepaid Plan Expiring",
    message: "Time to recharge! Keep your calls and data active. Click here to recharge in 1 tap.",
    icon: "smartphone",
    reference_type: "bbps_transaction",
    reference_id: "txn_recharge_1",
    action_url: "/bbps",
    screen: "BBPS",
  },
  bbps_transaction_status: {
    module: "bbps",
    type: "bbps_payment_success",
    title: "Payment Successful!",
    message: "Your payment of Rs. 850.00 for Tata Power was processed. A receipt has been generated.",
    icon: "receipt",
    reference_type: "bbps_transaction",
    reference_id: "txn_recharge_1",
    action_url: "/bbps",
    screen: "BBPS",
  },
  step_midday_goal_hook: {
    module: "fitness",
    type: "fitness_midday_hook",
    title: "Let's get moving!",
    message: "You've walked 1200 steps today. Take a quick stroll to hit your daily goal!",
    icon: "footprints",
    reference_type: "fitness_goal",
    reference_id: "midday_hook",
    action_url: "/fitness",
    screen: "Fitness",
  },
  step_almost_completed: {
    module: "fitness",
    type: "fitness_almost_completed",
    title: "Almost there!",
    message: "Only 1500 steps left to achieve your daily target. You can do it!",
    icon: "award",
    reference_type: "fitness_goal",
    reference_id: "almost_completed",
    action_url: "/fitness",
    screen: "Fitness",
  },
  step_goal_completed_reward: {
    module: "fitness",
    type: "fitness_reward_earned",
    title: "Daily Goal Achieved!",
    message: "Incredible job! You reached your step target and earned 50 Reward Coins!",
    icon: "footprints",
    reference_type: "fitness_reward",
    reference_id: "fit_reward_1",
    action_url: "/fitness/wallet",
    screen: "FitnessWallet",
  },
};

function getNotificationTypeKeys() {
  return Object.keys(notificationCatalog);
}

function getNotificationCatalogSummary() {
  return Object.entries(notificationCatalog).map(([key, value]) => ({
    key,
    module: value.module,
    type: value.type,
    title: value.title,
  }));
}

function buildNotificationPayload(type, overrides = {}) {
  const basePayload = notificationCatalog[type];

  if (!basePayload) {
    return null;
  }

  return {
    ...basePayload,
    ...overrides,
  };
}

module.exports = {
  notificationCatalog,
  getNotificationTypeKeys,
  getNotificationCatalogSummary,
  buildNotificationPayload,
};
