import { FiArrowRight, FiGrid, FiInbox, FiLayers, FiShield, FiShoppingBag, FiTrendingUp, FiXCircle } from "react-icons/fi";
import { Link } from "react-router-dom";
import { routes } from "../../../../../routes";

const workspaces = [
  { label: "Services & variants", description: "Browse the complete active service catalogue.", to: routes.service.catalog, Icon: FiLayers, tone: "bg-purple-50 text-[#852BAF]" },
  { label: "Service enquiries", description: "Review and progress incoming customer enquiries.", to: routes.service.enquiries, Icon: FiInbox, tone: "bg-amber-50 text-amber-600" },
  { label: "Service orders", description: "Track documentation, delivery and completion.", to: routes.service.orders, Icon: FiShoppingBag, tone: "bg-blue-50 text-blue-600" },
  { label: "Cancellations", description: "Review cancellation and refund requests.", to: routes.service.cancellations, Icon: FiXCircle, tone: "bg-red-50 text-red-600" },
];

export default function ServiceDashboard() {
  return <main className="space-y-7"><header className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-[#25103d] via-[#68258d] to-[#c33076] p-8 text-white shadow-[0_24px_65px_rgba(91,33,124,0.24)]"><div className="absolute -right-16 -top-24 h-72 w-72 rounded-full bg-white/10 blur-2xl" /><div className="relative"><span className="grid h-13 w-13 place-items-center rounded-2xl border border-white/20 bg-white/10"><FiGrid size={23} /></span><p className="mt-6 text-[10px] font-bold uppercase tracking-[0.25em] text-purple-200">Service manager workspace</p><h1 className="mt-1 text-3xl font-black sm:text-4xl">Service Operations Dashboard</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-purple-100/80">Manage the service catalogue, financial-service modules and the complete customer order lifecycle from one workspace.</p></div></header><section><div className="mb-4"><h2 className="text-lg font-black text-slate-900">Operations</h2><p className="text-xs text-slate-400">Your primary service-management workspaces</p></div><div className="grid gap-4 md:grid-cols-2">{workspaces.map(({ label, description, to, Icon, tone }) => <Link key={label} to={to} className="group rounded-2xl border border-purple-100 bg-white p-5 shadow-[0_12px_35px_rgba(67,31,91,0.06)] transition hover:-translate-y-0.5 hover:shadow-lg"><div className="flex items-start gap-4"><span className={`grid h-12 w-12 shrink-0 place-items-center rounded-xl ${tone}`}><Icon size={20} /></span><span className="min-w-0 flex-1"><span className="block font-extrabold text-slate-900">{label}</span><span className="mt-1 block text-sm leading-5 text-slate-500">{description}</span></span><FiArrowRight className="mt-3 text-slate-300 transition group-hover:translate-x-1 group-hover:text-[#852BAF]" /></div></Link>)}</div></section><section className="grid gap-4 md:grid-cols-2"><Link to={routes.service.finance.replace(":section?", "mutual-funds")} className="rounded-2xl border border-emerald-100 bg-gradient-to-br from-white to-emerald-50 p-6"><FiTrendingUp className="text-2xl text-emerald-600" /><h3 className="mt-4 font-black text-slate-900">Mutual Funds</h3><p className="mt-1 text-sm text-slate-500">Open the mutual-fund content workspace.</p></Link><Link to={routes.service.finance.replace(":section?", "insurance")} className="rounded-2xl border border-blue-100 bg-gradient-to-br from-white to-blue-50 p-6"><FiShield className="text-2xl text-blue-600" /><h3 className="mt-4 font-black text-slate-900">Insurance</h3><p className="mt-1 text-sm text-slate-500">Open the insurance management workspace.</p></Link></section></main>;
}
