import { useCallback, useEffect, useMemo, useState } from "react";
import { FiClock, FiEdit2, FiPlus, FiRefreshCw, FiSearch, FiTag, FiTrash2, FiZap } from "react-icons/fi";
import type { IconType } from "react-icons";
import { Link } from "react-router-dom";
import Swal from "sweetalert2";
import { api } from "../../../../common/api/api";
import { routes } from "../../../../routes";

type Status = "draft" | "active" | "archived";
interface Campaign { campaign_id: number; title: string; banner_image: string | null; start_at: string | null; end_at: string | null; status: Status; display_order: number; }
const date = (value: string | null) => value ? new Date(value).toLocaleString("en-IN", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" }) : "Not scheduled";

export default function FlashSaleList() {
  const [sales, setSales] = useState<Campaign[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState<"all" | Status>("all");
  const load = useCallback(async () => { try { setLoading(true); const response = await api.get("/campaign/campaigns", { params: { campaign_type: "flash_sale" } }); setSales(response.data?.data || []); } catch { await Swal.fire("Unable to load flash sales", "Please try again.", "error"); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => sales.filter((sale) => (status === "all" || sale.status === status) && sale.title.toLowerCase().includes(search.toLowerCase())), [sales, search, status]);
  const updateStatus = async (sale: Campaign, next: Status) => { await api.patch(`/campaign/campaigns/${sale.campaign_id}/status`, { status: next }); await load(); };
  const remove = async (sale: Campaign) => { const result = await Swal.fire({ title: "Delete flash sale?", text: sale.title, icon: "warning", showCancelButton: true, confirmButtonText: "Delete", confirmButtonColor: "#DC2626" }); if (!result.isConfirmed) return; await api.delete(`/campaign/campaigns/${sale.campaign_id}`); await load(); };
  const counts = { total: sales.length, active: sales.filter((x) => x.status === "active").length, draft: sales.filter((x) => x.status === "draft").length, archived: sales.filter((x) => x.status === "archived").length };
  const statCards: Array<{ label: string; value: number; Icon: IconType; color: string }> = [
    { label: "Total campaigns", value: counts.total, Icon: FiZap, color: "text-purple-700 bg-purple-50" },
    { label: "Active", value: counts.active, Icon: FiTag, color: "text-emerald-700 bg-emerald-50" },
    { label: "Draft", value: counts.draft, Icon: FiEdit2, color: "text-amber-700 bg-amber-50" },
    { label: "Archived", value: counts.archived, Icon: FiClock, color: "text-slate-600 bg-slate-100" },
  ];
  return <div className="space-y-6">
    <section className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-[#25103d] via-[#70248f] to-[#d63379] p-7 text-white shadow-2xl shadow-purple-200"><div className="absolute -right-16 -top-20 h-56 w-56 rounded-full bg-white/10 blur-2xl" /><div className="relative flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[0.22em] text-purple-200">Campaign studio</p><h1 className="mt-2 text-3xl font-black">Flash Sales</h1><p className="mt-2 max-w-xl text-sm text-purple-100/80">Schedule limited-time offers, curate variants and control campaign inventory.</p></div><Link to={routes.manager.flashSales.create} className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-extrabold text-[#852BAF] shadow-lg transition hover:-translate-y-0.5"><FiPlus /> Create Flash Sale</Link></div></section>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{statCards.map(({ label, value, Icon, color }) => <div key={label} className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><div className={`mb-4 grid h-10 w-10 place-items-center rounded-xl ${color}`}><Icon /></div><p className="text-xs font-bold uppercase tracking-wider text-gray-400">{label}</p><p className="mt-1 text-2xl font-black text-gray-900">{value}</p></div>)}</div>
    <section className="overflow-hidden rounded-3xl border border-purple-100 bg-white shadow-[0_18px_55px_rgba(67,31,91,0.08)]"><div className="flex flex-col gap-3 border-b border-gray-100 p-5 sm:flex-row"><label className="relative flex-1"><FiSearch className="absolute left-3.5 top-1/2 -translate-y-1/2 text-gray-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search flash sales..." className="w-full rounded-xl border border-gray-200 bg-gray-50 py-2.5 pl-10 pr-4 text-sm outline-none focus:border-purple-400 focus:bg-white focus:ring-4 focus:ring-purple-100" /></label><select value={status} onChange={(e) => setStatus(e.target.value as typeof status)} className="rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-sm font-semibold"><option value="all">All statuses</option><option value="draft">Draft</option><option value="active">Active</option><option value="archived">Archived</option></select><button onClick={() => void load()} className="grid h-11 w-11 place-items-center rounded-xl border border-gray-200 text-gray-500 hover:text-[#852BAF]"><FiRefreshCw /></button></div>
      <div className="overflow-x-auto">{loading ? <div className="grid min-h-72 place-items-center"><FiRefreshCw className="animate-spin text-3xl text-[#852BAF]" /></div> : <table className="min-w-full text-left text-sm"><thead className="bg-purple-50/60 text-[10px] font-black uppercase tracking-wider text-gray-500"><tr><th className="px-5 py-4">Campaign</th><th className="px-5 py-4">Schedule</th><th className="px-5 py-4">Order</th><th className="px-5 py-4">Status</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-gray-100">{filtered.map((sale) => <tr key={sale.campaign_id} className="hover:bg-purple-50/30"><td className="px-5 py-4"><div className="flex items-center gap-3">{sale.banner_image ? <img src={sale.banner_image} alt="" className="h-12 w-20 rounded-xl object-cover" /> : <span className="grid h-12 w-20 place-items-center rounded-xl bg-purple-50 text-[#852BAF]"><FiZap /></span>}<div><p className="font-extrabold text-gray-900">{sale.title}</p><p className="text-xs text-gray-400">Campaign #{sale.campaign_id}</p></div></div></td><td className="px-5 py-4"><p className="text-xs font-semibold text-gray-700">{date(sale.start_at)}</p><p className="mt-1 text-xs text-gray-400">to {date(sale.end_at)}</p></td><td className="px-5 py-4 font-bold text-gray-600">#{sale.display_order}</td><td className="px-5 py-4"><select value={sale.status} onChange={(e) => void updateStatus(sale, e.target.value as Status)} className={`rounded-full border-0 px-3 py-1.5 text-xs font-extrabold capitalize ${sale.status === "active" ? "bg-emerald-50 text-emerald-700" : sale.status === "draft" ? "bg-amber-50 text-amber-700" : "bg-gray-100 text-gray-500"}`}><option value="draft">Draft</option><option value="active">Active</option><option value="archived">Archived</option></select></td><td className="px-5 py-4"><div className="flex justify-end gap-2"><Link to={routes.manager.flashSales.edit.replace(":id", String(sale.campaign_id))} className="grid h-9 w-9 place-items-center rounded-xl bg-purple-50 text-[#852BAF] hover:bg-[#852BAF] hover:text-white"><FiEdit2 /></Link><button onClick={() => void remove(sale)} className="grid h-9 w-9 place-items-center rounded-xl bg-red-50 text-red-600 hover:bg-red-600 hover:text-white"><FiTrash2 /></button></div></td></tr>)}</tbody></table>}{!loading && !filtered.length && <p className="p-16 text-center text-sm text-gray-400">No flash sales match these filters.</p>}</div>
    </section>
  </div>;
}
